import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopHeader from "./component/header/topHeade/TopHeader";
import Hearder from "./component/header/Header/Hearder";
import NavBar from "./component/header/navBar/navBar";
import Footer from "./component/footer";
import PaymentFooter from "./component/section/PaymentFooter";
import { CartProvider } from "./context/CartContext";

// Import Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the document
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header Sections */}
        <TopHeader />
        <Hearder />
        <NavBar />

        {/* Main Content */}
        <CartProvider>{children}</CartProvider>
        
        

        {/* Footer */}
        <Footer />
        {/* PaymentFooter */}
        <PaymentFooter />
        
      </body>
    </html>
  );
}
